version: 2

root-markers:
  - .git/
  - .terraform/
  - main.tf
  - versions.tf

tools:
  vim-vint: &vim-vint
    prefix: "vim-vint"
    lint-command: "vint"
    lint-formats:
      - "%f:%l:%c: %m"

  markdownlint-cli2: &markdownlint-cli2
    prefix: "markdownlint-cli2"
    lint-command: "markdownlint-cli2 ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"

  textlint: &textlint
    prefix: "textlint"
    lint-command: "textlint --config ${XDG_CONFIG_HOME}/textlint/textlintrc --format compact ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f: line %l, col %c, %tnfo - %m"
      - "%f: line %l, col %c, %tarning - %m"
      - "%f: line %l, col %c, %trror - %m"

  tflint: &tflint
    prefix: "tflint"
    lint-command: "tflint --format compact --recursive --module"
    lint-stdin: true
    lint-formats:
      - ":%l:%c: %totice - %m"
      - ":%l:%c: %tarning - %m"
      - ":%l:%c: %trror - %m"
      - "%f:%l:%c: %totice - %m"
      - "%f:%l:%c: %tarning - %m"
      - "%f:%l:%c: %trror - %m"

  trivy-config: &trivy-config
    prefix: "trivy-config"
    lint-command: trivy config --tf-exclude-downloaded-modules --skip-dirs '.terraform' --format json . | jq -r '.Results[]? | .Target as $target | .Misconfigurations[]? | .Description as $description | .ID as $id | .Severity as $severity | .PrimaryURL as $primaryURL | .CauseMetadata | [$target, .StartLine, .EndLine, $severity, "[" + $id + "] " + $description + " see. " + $primaryURL] | @csv'
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '"%f",%l,%e,"%tNKNOWN","%m"'
      - '"%f",%l,%e,"%tOW","%m"'
      - '"%f",%l,%e,"%tEDIUM","%m"'
      - '"%f",%l,%e,"%tIGH","%m"'
      - '"%f",%l,%e,"%tRITICAL","%m"'
    lint-category-map:
      U: N
      L: N
      M: I
      H: W
      C: E

  hadolint: &hadolint
    prefix: "hadolint"
    lint-command: "hadolint --no-color"
    lint-formats:
      - "%f:%l %m"

  shellcheck: &shellcheck
    prefix: "shellcheck"
    lint-command: "shellcheck --format gcc"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  shfmt: &shfmt
    format-command: "shfmt --language-dialect bash --indent 4 --binary-next-line --case-indent --space-redirects --keep-padding"
    format-stdin: true

  jq: &jq
    format-command: "jq ."
    format-stdin: true

languages:
  vim:
    - <<: *vim-vint

  markdown:
    - <<: *markdownlint-cli2
    - <<: *textlint

  terraform:
    - <<: *tflint
    - <<: *trivy-config

  dockerfile:
    - <<: *hadolint

  sh:
    - <<: *shellcheck
    - <<: *shfmt

  json:
    - <<: *jq
