version: 2

root-markers:
  - .git/

tools:
  vim-vint: &vim-vint
    prefix: "vim-vint"
    lint-command: "vint"
    lint-formats:
      - "%f:%l:%c: %m"

  markdownlint-cli2: &markdownlint-cli2
    prefix: "markdownlint-cli2"
    lint-command: "markdownlint-cli2 ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"

  textlint: &textlint
    prefix: "textlint"
    lint-command: "textlint --config ${XDG_CONFIG_HOME}/textlint/textlintrc --format compact ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f: line %l, col %c, %tnfo - %m"
      - "%f: line %l, col %c, %tarning - %m"
      - "%f: line %l, col %c, %trror - %m"

languages:
  vim:
    - <<: *vim-vint

  markdown:
    - <<: *markdownlint-cli2
    - <<: *textlint
