version: 2

#log-level: 1
#log-file: /tmp/efm-langserver.log

root-markers:
  - .git/
  - .terraform/
  - main.tf
  - versions.tf

tools:
  vim-vint: &vim-vint
    prefix: "vim-vint"
    lint-command: "vint"
    lint-formats:
      - "%f:%l:%c: %m"

  markdownlint-cli2: &markdownlint-cli2
    prefix: "markdownlint-cli2"
    lint-command: "markdownlint-cli2 ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"

  textlint: &textlint
    prefix: "textlint"
    lint-command: "textlint --config ~/.config/textlint/textlintrc --format compact ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f: line %l, col %c, %tnfo - %m"
      - "%f: line %l, col %c, %tarning - %m"
      - "%f: line %l, col %c, %trror - %m"

  tflint: &tflint
    prefix: "tflint"
    lint-command: "tflint --format compact --recursive --call-module-type all"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - ":%l:%c: %totice - %m"
      - ":%l:%c: %tarning - %m"
      - ":%l:%c: %trror - %m"
      - "%f:%l:%c: %totice - %m"
      - "%f:%l:%c: %tarning - %m"
      - "%f:%l:%c: %trror - %m"

  trivy-config: &trivy-config
    prefix: "trivy-config"
    lint-command: trivy config --tf-exclude-downloaded-modules --skip-dirs '.terraform' --format sarif "${INPUT}" | jq --raw-output --from-file "${HOME}/.config/efm-langserver/sarif-to-errfmt.jq"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l-%e:%c-%k:%tONE:"%m"'
      - '%f:%l-%e:%c-%k:%tOTE:"%m"'
      - '%f:%l-%e:%c-%k:%tARNING:"%m"'
      - '%f:%l-%e:%c-%k:%tRROR:"%m"'

  docker-check: &docker-check
    prefix: "docker-check"
    lint-command: docker build --call 'check,format=json' -f "${INPUT}" . | jq --raw-output '[.warnings[] | .location.ranges[].start.line, .location.ranges[].end.line, "[" + .ruleName + "] " + .description] | @csv'
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%l,%e,"%m"'

  hadolint: &hadolint
    prefix: "hadolint"
    lint-command: "hadolint --no-color"
    lint-formats:
      - "%f:%l %m"

  shellcheck: &shellcheck
    prefix: "shellcheck"
    lint-command: "shellcheck --format gcc"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  shfmt: &shfmt
    format-command: "shfmt --language-dialect bash --indent 4 --binary-next-line --case-indent --space-redirects --keep-padding"
    format-stdin: true

  jq: &jq
    format-command: "jq ."
    format-stdin: true

  sql-formatter: &sql-formatter
    format-command: "sql-formatter --config ~/.config/sql-formatter/mysql.config.json"
    format-stdin: true

  actionlint: &actionlint
    lint-command: "actionlint -oneline ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  vim:
    - <<: *vim-vint

  markdown:
    - <<: *markdownlint-cli2
    - <<: *textlint

  terraform:
    - <<: *tflint
    - <<: *trivy-config

  dockerfile:
    - <<: *docker-check
    - <<: *hadolint

  sh:
    - <<: *shellcheck
    - <<: *shfmt

  json:
    - <<: *jq

  sql:
    - <<: *sql-formatter

  yaml:
    - <<: *actionlint
