source $MYVIMRC
if has('win32')
    set guifont=Inconsolata:h11:cANSI,Consolas:h11:cANSI
    set guifontwide=Migu_1M:h11:cSHIFTJIS,MS_Gothic:h11:cSHIFTJIS,MS_Mincho:h11:cSHIFTJIS
elseif has('mac')
    set guifont=Osaka-Mono:h16,Inconsolata:h16
    set guifontwide=Migu\ 1M:h16,Hiragino\ Maru\ Gothic\ Pro:w4:h16,Osaka:h16
else
    set guifont=Inconsolata\ 12,Monospace\ 12
    set guifontwide=Migu\ 1M,TakaoPGothic
endif
" iI|!1| ほげさn感じsfjsdlfkjsdfsldjfsふぁあかさたな浜やら和音
" ○○●◎➤➤➤➤➤➤➤➤➤➤➤☛☛☛☛☛☛☛☛☛
" oO0qQcCdD
"set listchars=eol:⏎,tab:➤‒,trail:⊠,extends:☛,precedes:☚,conceal:⇿,nbsp:⧈
command! ReloadGVimrc source $MYGVIMRC
set visualbell t_vb=
set lines=30
set columns=130
set colorcolumn=80,120
set guioptions-=T
set guioptions-=R
set guioptions-=r
set guioptions-=L
set guioptions-=l
set guioptions-=b
set guioptions-=m
" guiのタブを使わない、D&D で入替えができないため
set guioptions-=e
set showtabline=2
