source $MYVIMRC
if has('win32')
    set guifont=Inconsolata:h11:cANSI,Consolas:h11:cANSI
    set guifontwide=Migu_1M:h11:cSHIFTJIS,MS_Gothic:h11:cSHIFTJIS,MS_Mincho:h11:cSHIFTJIS
elseif has('mac')
    set guifont=Osaka-Mono:h16
else
    set guifont=Ricty\ 12,Inconsolata\ 12,Ubuntu\ Mono\ 12
    set guifontwide=Ricty\ 12,Migu\ 1M\ 12,TakaoGothic\ 12
endif
" iI|!1| ほげさn感じsfjsdlfkjsdfsldjfsふぁあかさたな浜やら和音
" ○○●◎➤➤➤➤➤➤➤➤➤➤➤☛☛☛☛☛☛☛☛☛
" oO0qQcCdD
"set listchars=eol:⏎,tab:➤‒,trail:⊠,extends:☛,precedes:☚,conceal:⇿,nbsp:⧈
command! ReloadGVimrc source $MYGVIMRC
set visualbell t_vb=
set lines=30
set columns=130
set colorcolumn=80,120
set guioptions-=T
set guioptions-=R
set guioptions-=r
set guioptions-=L
set guioptions-=l
set guioptions-=b
set guioptions-=m
" guiのタブを使わない、D&D で入替えができないため
set guioptions-=e
set showtabline=2
