#! /usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname "${0}")/.."

DOTFILE_ROOT_DIR="$(pwd)"
readonly DOTFILE_ROOT_DIR
readonly BACKUP_DIR="${DOTFILE_ROOT_DIR}/backup"

source "${DOTFILE_ROOT_DIR}/zsh/autoload/100-xdg.zsh"

function create_symlink() {
    local source_path="${1}"
    local target_path="${2}"
    local backup_name="${3}"

    echo "==> Creating symbolic link ${source_path} -> ${target_path}"

    if [ -L "${target_path}" ]; then
        echo "${target_path} symbolic link found. Unlinking ${target_path}."
        unlink "${target_path}"
    elif [ -e "${target_path}" ]; then
        echo "${target_path} found. Backing up to ${BACKUP_DIR}/${backup_name}"
        mv "${target_path}" "${BACKUP_DIR}/${backup_name}"
    fi

    ln -s "${source_path}" "${target_path}"

    echo -e "==> Symbolic link created successfully!\n"
}

echo "Start setup"

if [ ! -d "${BACKUP_DIR}" ]; then
    echo "Create ${BACKUP_DIR}"
    mkdir "${BACKUP_DIR}"
fi

# Setup ~/.config symlink
create_symlink "${DOTFILE_ROOT_DIR}" "${XDG_CONFIG_HOME}" "config"

if [ -f ~/.zshenv ]; then
    echo "${HOME}/.zshenv found. backup to ${BACKUP_DIR}/zshenv"
    mv ~/.zshenv "${BACKUP_DIR}/zshenv"
    echo "Create ~/.zshenv"
    echo "export ZDOTDIR=${XDG_CONFIG_HOME}/zsh" >~/.zshenv
else
    echo "Create ~/.zshenv"
    echo "export ZDOTDIR=${XDG_CONFIG_HOME}/zsh" >~/.zshenv
fi

# Setup ~/tool-versions symlink
create_symlink "${DOTFILE_ROOT_DIR}/asdf/tool-versions" "${HOME}/tool-versions" "tool-versions"

# Setup ~/.tflint.hcl symlink
create_symlink "${DOTFILE_ROOT_DIR}/tflint/tflint.hcl" "${HOME}/.tflint.hcl" "tflint.hcl"

if [ ! -d ~/.local/share/zsh ]; then
    echo "Create ~/.local/share/zsh"
    mkdir -p ~/.local/share/zsh
fi

echo "Finish setup!"
echo ""

"${DOTFILE_ROOT_DIR}/script/bootstrap"

