#! /usr/bin/env bash

set -eu
set -o pipefail

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

cd "$(dirname "${0}")/.."

DOTFILE_ROOT_DIR="$(pwd)"
readonly DOTFILE_ROOT_DIR
readonly BACKUP_DIR="${DOTFILE_ROOT_DIR}/backup"

source "${DOTFILE_ROOT_DIR}/zsh/autoload/100-xdg.zsh"

echo "Start setup"

if [ ! -d "${BACKUP_DIR}" ]; then
    echo "Create ${BACKUP_DIR}"
    mkdir "${BACKUP_DIR}"
fi

if [ -L ~/.config ]; then
    echo "${HOME}/.config symbolic link found. unlink ~/.config."
    unlink ~/.config
    echo "Create symbolic link ${DOTFILE_ROOT_DIR} ~/.config"
    ln -s "${DOTFILE_ROOT_DIR}" ~/.config
elif [ -d ~/.config ]; then
    echo "${HOME}/.config directory found. backup to ${BACKUP_DIR}/config"
    mv ~/.config "${BACKUP_DIR}/config"
    echo "Create symbolic link ${DOTFILE_ROOT_DIR} ~/.config"
    ln -s "${DOTFILE_ROOT_DIR}" ~/.config
else
    echo "Create symbolic link ${DOTFILE_ROOT_DIR} ~/.config"
    ln -s "${DOTFILE_ROOT_DIR}" ~/.config
fi

if [ -f ~/.zshenv ]; then
    echo "${HOME}/.zshenv found. backup to ${BACKUP_DIR}/zshenv"
    mv ~/.zshenv "${BACKUP_DIR}/zshenv"
    echo "Create ~/.zshenv"
    echo "export ZDOTDIR=${XDG_CONFIG_HOME}/zsh" >~/.zshenv
else
    echo "Create ~/.zshenv"
    echo "export ZDOTDIR=${XDG_CONFIG_HOME}/zsh" >~/.zshenv
fi

if [ -f ~/.bashrc ]; then
    echo "${HOME}/.bashrc found. backup to ${BACKUP_DIR}/bashrc"
    mv ~/.bashrc "${BACKUP_DIR}/bashrc"
    echo "Create ~/.bashrc"
    echo "source ${XDG_CONFIG_HOME}/bashrc" >~/.bashrc
else
    echo "Create ~/.bashrc"
    echo "source ${XDG_CONFIG_HOME}/bashrc" >~/.bashrc
fi

if [ -L ~/tool-versions ]; then
    echo "${HOME}/tool-versions symbolic link found. unlink ~/tool-versions."
    unlink ~/tool-versions
    echo "Create symbolic link ${DOTFILE_ROOT_DIR}/asdf/tool-versions ~/tool-versions"
    ln -s "${DOTFILE_ROOT_DIR}/asdf/tool-versions" ~/tool-versions
else
    echo "Create symbolic link ${DOTFILE_ROOT_DIR}/asdf/tool-versions ~/tool-versions"
    ln -s "${DOTFILE_ROOT_DIR}/asdf/tool-versions" ~/tool-versions
fi

if [ -L "${HOME}/.tflint.hcl" ]; then
    echo "${HOME}/.tflint.hcl symbolic link found. unlink ~/.tflint.hcl."
    unlink ~/.tflint.hcl
fi

echo "Create symbolic link ${DOTFILE_ROOT_DIR}/tflint/.tflint.hcl ~/.tflint.hcl"
ln -s "${DOTFILE_ROOT_DIR}/tflint/tflint.hcl" "${HOME}/.tflint.hcl"

if [ ! -d ~/.local/share/zsh ]; then
    echo "Create ~/.local/share/zsh"
    mkdir -p ~/.local/share/zsh
fi

echo "Finish setup!"
echo ""

"${DOTFILE_ROOT_DIR}/script/bootstrap"

