#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

readonly DOTFILE_ROOT_DIR="$(pwd)"
readonly BACKUP_DIR="$DOTFILE_ROOT_DIR/backup"

source $DOTFILE_ROOT_DIR/zsh/autoload/xdg.zsh

echo "Start setup"

if [ ! -d ${BACKUP_DIR} ] ; then
    echo "Create ${BACKUP_DIR}"
    mkdir ${BACKUP_DIR}
fi

if [ -L ~/.config ] ; then
    echo "~/.config symbolic link found. unlink ~/.config."
    unlink ~/.config
    echo "Create symbolic link ${DOTFILE_ROOT_DIR} ~/.config"
    ln -s ${DOTFILE_ROOT_DIR} ~/.config
elif [ -d ~/.config ] ; then
    echo "~/.config directory found. backup to ${BACKUP_DIR}/config"
    mv ~/.config ${BACKUP_DIR}/config
    echo "Create symbolic link ${DOTFILE_ROOT_DIR} ~/.config"
    ln -s ${DOTFILE_ROOT_DIR} ~/.config
else
    echo "Create symbolic link ${DOTFILE_ROOT_DIR} ~/.config"
    ln -s ${DOTFILE_ROOT_DIR} ~/.config
fi

if [ -f ~/.zshenv ] ; then
    echo "~/.zshenv found. backup to ${BACKUP_DIR}/zshenv"
    mv ~/.zshenv ${BACKUP_DIR}/zshenv
    echo "Create ~/.zshenv"
    echo "export ZDOTDIR=${XDG_CONFIG_HOME}/zsh" > ~/.zshenv
else
    echo "Create ~/.zshenv"
    echo "export ZDOTDIR=${XDG_CONFIG_HOME}/zsh" > ~/.zshenv
fi

if [ -f ~/.bashrc ] ; then
    echo "~/.bashrc found. backup to ${BACKUP_DIR}/bashrc"
    mv ~/.bashrc ${BACKUP_DIR}/bashrc
    echo "Create ~/.bashrc"
    echo "source ${XDG_CONFIG_HOME}/bashrc" > ~/.bashrc
else
    echo "Create ~/.bashrc"
    echo "source ${XDG_CONFIG_HOME}/bashrc" > ~/.bashrc
fi

if [ -L ~/.vim ] ; then
    echo "~/.vim symbolic link found. unlink ~/.vim."
    unlink ~/.vim
    echo "Create symbolic link ${DOTFILE_ROOT_DIR}/vim ~/.vim"
    ln -s ${DOTFILE_ROOT_DIR}/vim ~/.vim
elif [ -d ~/.vim ] ; then
    echo "~/.vim directory found. backup to ${BACKUP_DIR}/vim"
    mv ~/.vim ${BACKUP_DIR}/vim
    echo "Create symbolic link ${DOTFILE_ROOT_DIR}/vim ~/.vim"
    ln -s ${DOTFILE_ROOT_DIR}/vim ~/.vim
else
    echo "Create symbolic link ${DOTFILE_ROOT_DIR}/vim ~/.vim"
    ln -s ${DOTFILE_ROOT_DIR}/vim ~/.vim
fi

echo "Finish setup!"
echo ""

$DOTFILE_ROOT_DIR/script/bootstrap
