path=(
    $(brew --prefix)/bin
    $(brew --prefix)/sbin
    $(brew --prefix)/opt/curl/bin(N-/)
    $(brew --prefix)/opt/openssl@1.1/bin(N-/)
    $GOPATH/bin(N-/)
    $COMPOSER_BIN_DIR(N-/)
    $GEM_HOME/bin(N-/)
    $JAVA_HOME/bin(N-/)
    $XDG_CONFIG_HOME/bin(N-/)
    $HOME/.fastlane/bin(N-/)
    $path
)

alias be='bundle exec'
alias phpunit-coverage='phpunit --coverage-html reports --coverage-clover reports/coverage.xml'
alias tf='terraform'
alias tree='tree -N -C'
alias ls='ls -G'
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias chrome-incognito="chrome --incognito"
alias chrome-canary="/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary"
alias chrome-canary-incognito="chrome-canary --incognito"
alias plantuml_start='docker run --name plantuml-server --rm --env "PLANTUML_LIMIT_SIZE=8192" -d -p 8888:8080 plantuml/plantuml-server'
alias plantuml_stop='docker stop plantuml-server'
alias k8s_dashbord_start='kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc7/aio/deploy/recommended.yaml'
alias k8s_dashbord_stop='kubectl delete -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc7/aio/deploy/recommended.yaml'

eval "$(nodenv init -)"
eval "$(rbenv init -)"
eval "$(direnv hook zsh)"

export DOCKER_BUILDKIT=1
export LESSCHARSET=utf-8
export JAVA_HOME=$(/usr/libexec/java_home)
export ANDROID_HOME="${HOME}/Library/Android/sdk"
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export NODE_PATH="$(npm root -g)"

for file in $(ls $ZDOTDIR/autoload/*.zsh) ;
do
    source $file
done
